#!/bin/bash
JAVA_32=$(alternatives --display java | grep family | grep i386 | cut -d' ' -f1)
alternatives --set java ${JAVA_32}
JAVAC_32=$(alternatives --display javac | grep family | grep i386 | cut -d' ' -f1)
# Maven actually uses javac, not java
alternatives --set javac ${JAVAC_32}
exit $? 
